apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: default
  labels:
    app: mysql5.7
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi