apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: mysql-pvc
    namespace: default
  hostPath:
    path: /home/work/share/model-db
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem